version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: workspace
  test:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: workspace
      - run: npm test
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: workspace
      - run: npm run lint
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
