version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: /tmp/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test
workflows:
  version: 2
  pipeline:
    jobs:
      - test

